server:
  port: 8081
spring:
#  config:
#    import: db-config.yaml,logging.yaml
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:fedtestdb}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    hikari:
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update